### ISSUE TITLE
getErrors missing after migration to 2.0.0

### ISSUE THREAD

**Issue by mgreer** [ctrlplusb/react-async-component#82]
Migrating from previous release to 2.0.0 and webpack 4, I suddenly get this error:
```
Uncaught (in promise) TypeError: (0 , n.getError) is not a function
```
Curious, since the AsyncComponent class should be setting this method, and class seems to have shouldRehydrate.
Error is here:
```js
        // browser
        if (env === 'browser') {
          var _state$asyncComponent = state.asyncComponents,
              shouldRehydrate = _state$asyncComponent.shouldRehydrate,
              getError = _state$asyncComponent.getError; // <== error is here

          var error = getError(state.id);
          if (error) {
            state.error = error;
            return false;
          }
          return shouldRehydrate(state.id) ? doResolve() : false;
        }
```
Previous release worked in webpack 4.

**Comment by SleepWalker** [comment]
Another one issue is that when you are using SSR, than after upgrade to v2, the `bootstrap` logic will be broken on the client because of undefined return from the bootstrap on the server side:

```js
      const doResolve = () =>
        this.resolveModule().then(
          module => (module === undefined ? false : undefined),
        )
```
